update links
collective/collective.getpid pull request #2
Opened 2022-02-14 22:46 UTC by Arhell

2022-02-15 07:43 UTC, ale-rt requested changes

2022-02-15 07:43 UTC, ale-rt commented on collective/__init__.py
> +# See https://peak.telecommunity.com/DevCenter/setuptools#namespace-packages
The link is broken

2022-02-15 07:43 UTC, ale-rt commented on setup.py
> +      # https://pypi.python.org/pypi?%3Aaction=list_classifiers
```suggestion
      # https://pypi.org/classifiers/
```

2022-02-16 08:57 UTC, Arhell commented on collective/__init__.py
> +# See https://peak.telecommunity.com/DevCenter/setuptools#namespace-packages
Thank you, I will delete

2022-02-16 08:57 UTC, Arhell commented on setup.py
> +      # https://pypi.python.org/pypi?%3Aaction=list_classifiers
Thank you

2022-02-17 09:44 UTC, merged